### ISSUE TITLE
Healthspan

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/lifespan_contraception#4]
@Mike-Garratt and @mlagisz (I am doing this for the second time - first time did not seem to send)

Here are the preliminary results  - there are not many differences (maybe a good thing - as castration is not affecting these health parameters)

Pathology decreases (so does immunity but based on just one study - we should not consider anything fewer than 3 studies at least?)

<img width="1645" alt="Screenshot 2024-11-17 at 12 21 34 pm" src="https://github.com/user-attachments/assets/6cef59dd-606b-40df-a7e6-434bd807dd7c">

Yes, chat soon @Mike-Garratt

**Comment by Mike-Garratt** [comment]
Hi Shinichi,

Sex has a big impact on these results I think. Can you split the analysis for males and females separately? And/or test whether sex is a moderator?

Chat in a bit!

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Monday, 18 November 2024 at 10:48 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: [itchyshin/lifespan_contraception] Healthspan (Issue #4)

@Mike-Garratt<https://github.com/Mike-Garratt> and @mlagisz<https://github.com/mlagisz> (I am doing this for the second time - first time did not seem to send)

Here are the preliminary results - there are not many differences (maybe a good thing - as castration is not affecting these health parameters)

Pathology decreases (so does immunity but based on just one study - we should not consider anything fewer than 3 studies at least?)
Screenshot.2024-11-17.at.12.21.34.pm.png (view on web)<https://github.com/user-attachments/assets/6cef59dd-606b-40df-a7e6-434bd807dd7c>

Yes, chat soon @Mike-Garratt<https://github.com/Mike-Garratt>

**Comment by itchyshin** [comment]
here it is

<img width="1309" alt="Screenshot 2024-11-17 at 15 02 17" src="https://github.com/user-attachments/assets/5c1da56c-48a9-4925-becd-3cd008a4f953">

**Comment by itchyshin** [comment]
@Mike-Garratt here is an update

## Overall effect

13% increase in healthspan or related things

<img width="977" alt="Screenshot 2024-11-18 at 10 35 37" src="https://github.com/user-attachments/assets/bc5bc156-7ec3-47d7-a350-0e76d319156d">

## Sex specific effect

22% increase in females while 0.5% (no effect) in males

No overall effect on males but females sig effect
<img width="983" alt="Screenshot 2024-11-18 at 10 35 22" src="https://github.com/user-attachments/assets/350690ad-132b-4934-9e8d-f2d7f3ba277e">


## Sub-measures

Some interesting patterns - the female positive effect of castration comes from not getting breast cancer?
<img width="838" alt="Screenshot 2024-11-18 at 10 36 12" src="https://github.com/user-attachments/assets/0229860c-efe2-423c-b56b-1bfad79fe548">



## Sex x sub-measure


<img width="931" alt="Screenshot 2024-11-18 at 10 38 01" src="https://github.com/user-attachments/assets/3d8549a5-a62e-4631-a89d-9732e4ad44d2">

**Comment by Mike-Garratt** [comment]
Hi @Shinichi ***@***.***>

I am still fairly sure that the direction of change for some of the effect sizes must be wrong as “male strength/balance” goes in a positive direction and some of the other variables look to be going the wrong way too. I think male cognition only has one negative value or two slightly negative.

Yep, I think what we will see is that there is a big positive effect of ovariectomy on female breast cancer but most of the other variables go in the other direction.

If you think it is easier for me just to switch everything around in the raw datafile so that everything goes in one direction then I can do that?

Thanks for all your work!

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Tuesday, 19 November 2024 at 6:50 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Healthspan (Issue #4)

@Mike-Garratt<https://github.com/Mike-Garratt> here is an update

Overall effect

13% increase in healthspan or related things
Screenshot.2024-11-18.at.10.35.37.png (view on web)<https://github.com/user-attachments/assets/bc5bc156-7ec3-47d7-a350-0e76d319156d>
Sex specific effect

22% increase in females while 0.5% (no effect) in males

No overall effect on males but females sig effect
Screenshot.2024-11-18.at.10.35.22.png (view on web)<https://github.com/user-attachments/assets/350690ad-132b-4934-9e8d-f2d7f3ba277e>

Sub-measures

Some interesting patterns - the female positive effect of castration comes from not getting breast cancer?
Screenshot.2024-11-18.at.10.36.12.png (view on web)<https://github.com/user-attachments/assets/0229860c-efe2-423c-b56b-1bfad79fe548>

Sex x sub-measure
Screenshot.2024-11-18.at.10.38.01.png (view on web)<https://github.com/user-attachments/assets/3d8549a5-a62e-4631-a89d-9732e4ad44d2>

**Comment by itchyshin** [comment]
@Mike-Garratt 

Sorry I found a mistake in my coding (I was flipping everything), but now I get something which you may not expected

I used this (I am flipping one which is "Decreased" by multiplying -1 (and Increase I multiple by 1 so not change) - there was a typo in my previous code

```
dat$direction <- ifelse(dat$direction.of.improved.health == "Increased", 1, -1)

dat$yi <- dat$yi * dat$direction
```

So hopefully, this was correct. And results make sense (the model has strains which needs checking and also all other non-indepdence is corrected as well as sample sizes) 

Overall effect positive

<img width="1008" alt="Screenshot 2024-11-18 at 11 57 04" src="https://github.com/user-attachments/assets/2225f780-a6d4-46c8-b20f-1f4d5e47c5a8">


No sex effect

<img width="1008" alt="Screenshot 2024-11-18 at 11 57 26" src="https://github.com/user-attachments/assets/42fa7b04-bef0-47a0-86d6-cd2ef87c6e04">

These are in different categories


<img width="854" alt="Screenshot 2024-11-18 at 11 57 45" src="https://github.com/user-attachments/assets/077925fc-5bb6-4cfa-8f01-f38214ed53f8">

<img width="857" alt="Screenshot 2024-11-18 at 11 57 57" src="https://github.com/user-attachments/assets/cfc429dd-2a3a-42bf-afe2-1b2a1b6985cc">

**Comment by Mike-Garratt** [comment]
Hi Shinichi,

Thanks sounds good. Can I also see the sex by category effect? This will show me the data in a more familiar way and I am pretty sure some of these go in different directions in each sex.

Thanks for your help,

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Tuesday, 19 November 2024 at 8:00 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Healthspan (Issue #4)

@Mike-Garratt<https://github.com/Mike-Garratt>

Sorry I found a mistake in my coding (I was flipping everything), but now I get something which you may not expected

I used this (I am flipping one which is "Decreased" by multiplying -1 (and Increase I multiple by 1 so not change) - there was a typo in my previous code

dat$direction <- ifelse(dat$direction.of.improved.health == "Increased", 1, -1)



dat$yi <- dat$yi * dat$direction

So hopefully, this was correct. And results make sense (the model has strains which needs checking and also all other non-indepdence is corrected as well as sample sizes)

Overall effect positive
Screenshot.2024-11-18.at.11.57.04.png (view on web)<https://github.com/user-attachments/assets/2225f780-a6d4-46c8-b20f-1f4d5e47c5a8>

No sex effect
Screenshot.2024-11-18.at.11.57.26.png (view on web)<https://github.com/user-attachments/assets/42fa7b04-bef0-47a0-86d6-cd2ef87c6e04>

These are in different categories
Screenshot.2024-11-18.at.11.57.45.png (view on web)<https://github.com/user-attachments/assets/077925fc-5bb6-4cfa-8f01-f38214ed53f8> Screenshot.2024-11-18.at.11.57.57.png (view on web)<https://github.com/user-attachments/assets/cfc429dd-2a3a-42bf-afe2-1b2a1b6985cc>

**Comment by itchyshin** [comment]
@Mike-Garratt - the last fig is sex x different categories (and I can see some of these there are some sex effects)

**Comment by Mike-Garratt** [comment]
Excellent, I missed that second plot. Yep, this looks consistent with what I was thinking! So female effect is mainly due to reduced mammary cancers and there are negative effects on a couple of variables. Male effect is mostly strongly linked to improved cognition, strength, and non-tumor pathology.

Thanks!

Mike

From: Shinichi Nakagawa ***@***.***>
Date: Tuesday, 19 November 2024 at 8:17 AM
To: itchyshin/lifespan_contraception ***@***.***>
Cc: Mike Garratt ***@***.***>, Mention ***@***.***>
Subject: Re: [itchyshin/lifespan_contraception] Healthspan (Issue #4)

@Mike-Garratt<https://github.com/Mike-Garratt> - the last fig is sex x different categories (and I can see some of these there are some sex effects)

**Comment by itchyshin** [comment]
Cool @Mike-Garratt - I am on the causes of the death stuff - I think you were right about deleting some of these very small sample size ones (which were creating some artifacts - will report soon)
